import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='#' />
      </Head>

      <main className='text-3xl underline'>Hello, world!</main>

      <footer></footer>
    </div>
  )
}
